### ISSUE TITLE
Execution failing

### ISSUE THREAD

**Issue by tksharpless** [MarcioCerqueira/RealTimeDepthDiffusion#1]
Building on a gaming laptop with MSVC 2017/CUDA 10.1.  App starts OK and displays images but reports error:
GPULoadWeights: invalid device symbol
pressing 'd' gives the additional error messages:
GPUMatrixFreeSolver: no kernel image is available for execution on the device
GPUMatrixFreeSolver: no kernel image is available for execution on the device
GPUMatrixFreeSolver: no kernel image is available for execution on the device
GPUMatrixFreeSolver: no kernel image is available for execution on the device
GPUMatrixFreeSolver: no kernel image is available for execution on the device
These look to me like initialization problems.  Can you suggest how to find the cause?

**Comment by MarcioCerqueira** [comment]
I suffered from that problem when I was setting the wrong CUDA architecture during compilation. For instance, although the compute capability of my GPU (NVIDIA GeForce MX110) is 6.1, I had to set "compute_50,sm_50" to make the application work. I used the comment provided by VahidN in [this link](https://stackoverflow.com/questions/22364926/cuda-invalid-device-symbol-error) as a reference to solve this problem.

**Comment by tksharpless** [comment]
Thanks, Marcio
Do you happen to know how those nvcc architecture parameters get set when building with Microsoft Visual Studio?  Since cuda support is highly automatic on Windows, I would have assumed that the nVidia installed s/w would take care of matching the nvcc parameters to the local gpu.

**Comment by tksharpless** [comment]
OK I found the nvcc architecture arguments in the MSVCC project properties.  And they are set to compute_35,sm_35, which is apparently the minimum supported by the installed cuda toolkit 10.1.  However according to the Wikipedia article my GTX 680M gpu is cc 3.0.  So I tried editing the params and was able to set them to _30, got no build error but same runtime error.

**Comment by MarcioCerqueira** [comment]
Hi!

I would suggest you to take a look at your NVIDIA CUDA Samples. There, you can open any of the pre-configured Visual Studio projects and see which nvcc arguments they are using. In my personal computer, for instance, a single Visual Studio project has the following arguments: 

CUDA C/C++ -> Device -> Code Generation: "compute_35,sm_35;compute_37,sm_37;compute_50,sm_50;compute_52,sm_52;compute_60,sm_60;compute_61,sm_61;compute_70,sm_70;compute_75,sm_75;compute_80,sm_80;compute_86,sm_86;"

**Comment by tksharpless** [comment]
The cuda 10.1 samples do build and run OK.  Those VC projects contain a series of device architecture flags beginning with _30, which is right for my gpu.  I don't know how the default for the rtdd project got set to _35, but if I edit it to _30, rtdd runs without error.  This project was generated by Cmake, so I guess I need to find how to specify the right flags to Cmake.

**Comment by tksharpless** [comment]
This Cmake formula makes MSVC generate the right nvcc flags
`target_compile_options( RealTimeDepthDiffusion 
	PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:
		-gencode arch=compute_30,code=sm_30
    >)
`
BTW I would be happy to contribute my Cmake script to the project, as others may find it helpful

**Comment by MarcioCerqueira** [comment]
Nice! I would be pleased if you could submit a pull request with the cmake file.
