### ISSUE TITLE
Runs under Visual Studio but fails from command line

### ISSUE THREAD

**Issue by tksharpless** [MarcioCerqueira/RealTimeDepthDiffusion#2]
Hi Marcio
Well, I thought I had a working build, but have encountered a really strange problem:  the app runs fine when started from within Visual Studio, but when I try to run it as a command I get
`OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.1-dev) Error: Assertion failed (!_src.empty()) in cv::cvtColor, file c:\opencv4\opencv\modules\imgproc\src\color.cpp, line 182`
This happens both with powershell and with the 'VS native tools command prompt' (which has the same environment settings as VS) and is true for both debug and release builds.  In all cases I am launching the app from a directory that contains all the needed OpenCV dlls.

I have never seen this before and wonder if you have any insight.

**Comment by tksharpless** [comment]
Solved.  My mistake.  I had ommited '-i' before the input filename on command line.  So no file was loaded; and the first time that Mat was used is in a cvtcolor call.
I have added some code to check for command line errors so other users will not be so mystified.

**Comment by MarcioCerqueira** [comment]
Great! Indeed, I do not check whether the '-i' command line is given for the application. Thanks!
